# Generated by Django 5.2.1 on 2025-06-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={"ordering": ["-created_at"], "verbose_name_plural": "Teams"},
        ),
        migrations.AddField(
            model_name="task",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
